# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created: Tue Feb 19 17:04:58 2013
#      by: PyQt4 UI code generator 4.9.6
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1018, 829)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/images/Images/headerImage.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.motor0Slider = QtGui.QSlider(self.groupBox)
        self.motor0Slider.setOrientation(QtCore.Qt.Vertical)
        self.motor0Slider.setObjectName(_fromUtf8("motor0Slider"))
        self.horizontalLayout.addWidget(self.motor0Slider)
        spacerItem1 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.motor0SpinBox = QtGui.QSpinBox(self.groupBox)
        self.motor0SpinBox.setObjectName(_fromUtf8("motor0SpinBox"))
        self.verticalLayout.addWidget(self.motor0SpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        spacerItem2 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.motor1Slider = QtGui.QSlider(self.groupBox_2)
        self.motor1Slider.setOrientation(QtCore.Qt.Vertical)
        self.motor1Slider.setObjectName(_fromUtf8("motor1Slider"))
        self.horizontalLayout_5.addWidget(self.motor1Slider)
        spacerItem3 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.motor1SpinBox = QtGui.QSpinBox(self.groupBox_2)
        self.motor1SpinBox.setObjectName(_fromUtf8("motor1SpinBox"))
        self.verticalLayout_6.addWidget(self.motor1SpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem4 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.motor2Slider = QtGui.QSlider(self.groupBox_3)
        self.motor2Slider.setOrientation(QtCore.Qt.Vertical)
        self.motor2Slider.setObjectName(_fromUtf8("motor2Slider"))
        self.horizontalLayout_6.addWidget(self.motor2Slider)
        spacerItem5 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem5)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.motor2SpinBox = QtGui.QSpinBox(self.groupBox_3)
        self.motor2SpinBox.setObjectName(_fromUtf8("motor2SpinBox"))
        self.verticalLayout_7.addWidget(self.motor2SpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem6 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem6)
        self.motor3Slider = QtGui.QSlider(self.groupBox_4)
        self.motor3Slider.setOrientation(QtCore.Qt.Vertical)
        self.motor3Slider.setObjectName(_fromUtf8("motor3Slider"))
        self.horizontalLayout_7.addWidget(self.motor3Slider)
        spacerItem7 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem7)
        self.verticalLayout_8.addLayout(self.horizontalLayout_7)
        self.motor3SpinBox = QtGui.QSpinBox(self.groupBox_4)
        self.motor3SpinBox.setObjectName(_fromUtf8("motor3SpinBox"))
        self.verticalLayout_8.addWidget(self.motor3SpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.line = QtGui.QFrame(self.tab)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout_3.addWidget(self.line)
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        spacerItem8 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem8)
        self.masterMotorSlider = QtGui.QSlider(self.groupBox_5)
        self.masterMotorSlider.setOrientation(QtCore.Qt.Vertical)
        self.masterMotorSlider.setObjectName(_fromUtf8("masterMotorSlider"))
        self.horizontalLayout_8.addWidget(self.masterMotorSlider)
        spacerItem9 = QtGui.QSpacerItem(13, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.verticalLayout_9.addLayout(self.horizontalLayout_8)
        self.masterMotorSpinBox = QtGui.QSpinBox(self.groupBox_5)
        self.masterMotorSpinBox.setObjectName(_fromUtf8("masterMotorSpinBox"))
        self.verticalLayout_9.addWidget(self.masterMotorSpinBox)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox_7)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_8 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_8)
        self.lineEdit.setStyleSheet(_fromUtf8("background-color: rgb(6, 5, 4);\n"
"color: rgb(64, 181, 64);\n"
"font: 9pt \"Monospace\";"))
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_9)
        self.lineEdit_2.setStyleSheet(_fromUtf8("background-color: rgb(6, 5, 4);\n"
"color: rgb(64, 181, 64);\n"
"font: 9pt \"Monospace\";"))
        self.lineEdit_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_2.addWidget(self.lineEdit_2, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_9)
        self.groupBox_10 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit_3 = QtGui.QLineEdit(self.groupBox_10)
        self.lineEdit_3.setStyleSheet(_fromUtf8("background-color: rgb(6, 5, 4);\n"
"color: rgb(64, 181, 64);\n"
"font: 9pt \"Monospace\";"))
        self.lineEdit_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_3.setObjectName(_fromUtf8("lineEdit_3"))
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_10)
        self.verticalLayout_3.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.comboBox = QtGui.QComboBox(self.groupBox_6)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.comboBox.addItem(_fromUtf8(""))
        self.comboBox.addItem(_fromUtf8(""))
        self.verticalLayout_2.addWidget(self.comboBox)
        self.pushButton_2 = QtGui.QPushButton(self.groupBox_6)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_3.addWidget(self.groupBox_6)
        self.pushButton = QtGui.QPushButton(self.tab)
        font = QtGui.QFont()
        font.setPointSize(72)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_3.addWidget(self.pushButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        self.plainTextEdit = QtGui.QPlainTextEdit(self.tab)
        self.plainTextEdit.setAutoFillBackground(False)
        self.plainTextEdit.setStyleSheet(_fromUtf8("background-color: rgb(6, 5, 4);\n"
"color: rgb(64, 181, 64);\n"
"font: 9pt \"Monospace\";"))
        self.plainTextEdit.setObjectName(_fromUtf8("plainTextEdit"))
        self.verticalLayout_4.addWidget(self.plainTextEdit)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_5.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1018, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.motor0SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor0Slider.setValue)
        QtCore.QObject.connect(self.motor3Slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3SpinBox.setValue)
        QtCore.QObject.connect(self.masterMotorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor0Slider.setValue)
        QtCore.QObject.connect(self.motor0Slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor0SpinBox.setValue)
        QtCore.QObject.connect(self.motor1SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1Slider.setValue)
        QtCore.QObject.connect(self.motor1Slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1SpinBox.setValue)
        QtCore.QObject.connect(self.motor2SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2Slider.setValue)
        QtCore.QObject.connect(self.motor3SpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3Slider.setValue)
        QtCore.QObject.connect(self.motor2Slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2SpinBox.setValue)
        QtCore.QObject.connect(self.masterMotorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.masterMotorSpinBox.setValue)
        QtCore.QObject.connect(self.masterMotorSpinBox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.masterMotorSlider.setValue)
        QtCore.QObject.connect(self.masterMotorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor3Slider.setValue)
        QtCore.QObject.connect(self.masterMotorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor2Slider.setValue)
        QtCore.QObject.connect(self.masterMotorSlider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.motor1Slider.setValue)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Motor A", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Motor B", None))
        self.groupBox_3.setTitle(_translate("MainWindow", "Motor C", None))
        self.groupBox_4.setTitle(_translate("MainWindow", "Motor D", None))
        self.groupBox_5.setTitle(_translate("MainWindow", "Master", None))
        self.groupBox_7.setTitle(_translate("MainWindow", "Accelerometer", None))
        self.groupBox_8.setTitle(_translate("MainWindow", "X-Axis", None))
        self.groupBox_9.setTitle(_translate("MainWindow", "X-Axis", None))
        self.groupBox_10.setTitle(_translate("MainWindow", "X-Axis", None))
        self.groupBox_6.setTitle(_translate("MainWindow", "Meower", None))
        self.comboBox.setItemText(0, _translate("MainWindow", "Meow1.wav", None))
        self.comboBox.setItemText(1, _translate("MainWindow", "SurpriseMFcker.wav", None))
        self.pushButton_2.setText(_translate("MainWindow", "Launch", None))
        self.pushButton.setText(_translate("MainWindow", "ABORT", None))
        self.plainTextEdit.setPlainText(_translate("MainWindow", "[*] Wilfred is booting up... Done!\n"
"[*] Initalizing Drivers...   Done!\n"
"[+] MotorA: speed set to 50", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Motor Control", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))

import resources_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

